projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://eu1.prisma.sh/max237-27f373/blog01/dev
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml